[fonts]
-- font_family      M+CodeLat50NerdFont
-- font_family      Iosevka Comfy
-- font_family      family="Spleen 12x24" 
font_family      family="ProFont IIx Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 15.0
-- text_composition_strategy legacy

[options]
confirm_os_window_close 0
enable_audio_bell no

-- modify_font cell_height 130%
window_padding_width 15
-- cursor_trail 3
shell_integration no-cursor
cursor_shape block
cursor_shape block 
cursor_shape_unfocused hollow
cursor_blink no 

[colors]
(nano)
# foreground              #2e3338
# background              #ffffff

(yabuki)
foreground              #f5f5dc
background              #080808

[palette]
color0 #e2e2e2
color8 #ababab

color1 #ca0043
color9 #f30052

color2  #407f00
color10 #4f9a00

color3  #926200
color11 #b07700

color4 #3d3d3d
color12 #000000

color5  #a200d1
color13 #c301fb

color6  #007d7d
color14 #009797

color7  #6a6a6a
color15 #101010
