theme = "gruvbox-material-transparent"

[editor]
line-number = "relative"

cursorline = true
color-modes = true

true-color = true

indent-guides.render = true
indent-guides.character = "┊"

auto-completion = true
path-completion = true

[editor.lsp]
display-color-swatches = true

[editor.statusline]
left = [
  "mode",                        
  "file-name",                   
  "file-modification-indicator"
]
right = [
  "diagnostics",
  "register",                    
  "position",                    
  "primary-selection-length",   
  "selections",                  
  "position-percentage",         
  "file-type",                   
  "spacer"                       
]

mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
