# Bocchi The Rock theme desmoow modified
 
rainbow = [ "accent1", "accent3", "accent4", { fg = "accent2", modifiers = ["bold"] }]
"type" = "white"
"constant" = "white"
"constant.builtin" = { fg = "white", modifiers = ["italic", "bold"] }
"constant.builtin.boolean" = "white"
"constant.numeric" = "white"
"string" = "white"
"string.special" = "white"
"comment" = { fg = "gray", modifiers = ["italic"] }
"variable" = "white"
"variable.builtin" = { fg = "white", modifiers = ["italic", "bold"] }
"variable.parameter" = "white"
"variable.other.member" = "accent1"
"punctuation" = "gray"
"punctuation.delimiter" = "gray"
"punctuation.bracket" = "accent1"
"punctuation.special" = "accent1"
"keyword" = "accent1"
"keyword.operator" = "accent1"
"keyword.directive" = "accent1"
"keyword.storage" = "accent1"
"operator" = "accent1"
"function" = "accent1"
"function.macro" = "accent1"
"tag" = "accent1"
"namespace" = { fg = "white", modifiers = ["italic", "bold"] }
"attribute" = { fg = "accent1", modifiers = ["italic", "bold"] }
"constructor" = "accent1"
"module" = "white"
"special" = "accent1"

"markup.heading.1" = { fg = "accent1", modifiers = ["bold"] }
"markup.heading.2" = { fg = "accent1", modifiers = ["bold"] }
"markup.heading.3" = { fg = "white", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic", "bold"] }
"markup.link.url" = { fg = "accent1", underline = { style = "line" } }
"markup.link.text" = "white"

"diff.plus" = "accent1"
"diff.delta" = "accent2"
"diff.minus" = "accent4"

"ui.background" = { bg = "bg_dim" }
"ui.cursor" = { fg = "bg1", bg = "grey2" }
"ui.cursor.insert" = { fg = "bg0", bg = "grey1" }
"ui.cursor.select" = { fg = "bg0", bg = "accent2" }
"ui.cursor.primary" = { fg = "bg_dim", bg = "accent3" }
"ui.cursor.match" = { fg = "white", bg = "bg5" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.cursorcolumn.primary" = { bg = "bg1" }
"ui.cursorcolumn.secondary" = { bg = "bg1" }
"ui.selection" = { bg = "bg5" }
"ui.linenr" = "linenr_gray"
"ui.linenr.selected" = "accent1"
"ui.statusline" = { fg = "grey2", bg = "bg0" }
"ui.statusline.inactive" = { fg = "grey0", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "accent1", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "accent3", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "accent2", modifiers = ["bold"] }
"ui.bufferline" = { fg = "grey2", bg = "bg0" }
"ui.bufferline.active" = { fg = "bg0", bg = "accent1", modifiers = ["bold"] }
"ui.popup" = { fg = "grey2", bg = "bg0" }
"ui.window" = { fg = "bg4", bg = "bg0" }
"ui.help" = { fg = "white", bg = "bg0" }
"ui.text" = "white"
"ui.text.directory" = { fg = "accent1" }
"ui.text.focus" = "white"
"ui.menu" = { fg = "white", bg = "bg0" }
"ui.menu.selected" = { fg = "bg0", bg = "accent1" }
"ui.virtual.ruler" = { bg = "bg0" }
"ui.virtual.jump-label" = { fg = "accent3", modifiers = ["bold"] }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg5" }
"ui.virtual.inlay-hint" = { fg = "grey0" }
"ui.virtual.wrap" = { fg = "grey0" }

"hint" = "accent2"
"info" = { fg = "accent3", modifiers = ["bold"] }
"warning" = "accent3"
"error" = "accent4"

"diagnostic.hint" = { underline = { color = "accent2", style = "dotted" } }
"diagnostic.info" = { underline = { color = "accent1", style = "dotted" } }
"diagnostic.warning" = { underline = { color = "accent3", style = "dotted" } }
"diagnostic.error" = { underline = { color = "accent4", style = "dotted" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

[palette]
# bg_dim = "#292222"
# bg0 = "#403333"
# bg1 = "#403333"
# bg3 = "#403333"
# bg4 = "#403333"
# bg5 = "#806666"
# fg = "#403333"

# grey0 = "#403333"
# grey1 = "#403333"
# grey2 = "#403333"

bg_dim = "#1e2326"
bg0 = "#272e33"
bg1 = "#2e383c"
bg3 = "#414b50"
bg4 = "#495156"
bg5 = "#4f5b58"
fg = "#d3c6aa"

grey0 = "#7a8478"
grey1 = "#403333"
grey2 = "#9da9a0"

linenr_gray = "#5a6468"
linenr_gray_selected = "#6a7478"

white = "#dddddd"
gray = "#9da9a0"

accent1 = "#ffa6c9"       #  primary accent
accent2 = "#4a8bc2"       # secondary accent
accent3 = "#ffd166"       # tertiary accent
accent4 = "#e76f51"       # warnings and errors
